version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      boto:
        applies-to: version-updates
        patterns:
        - "boto*"
        - "s3transfer"
        update-types:
        - "minor"
    ignore:
      - dependency-name: "boto*"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "mypy-boto*"
        update-types: ["version-update:semver-patch"]
